"""Inspirations from Mythic Bastionland (pages 28-171).

Each page has a set of inspirational prompts across 13 categories.
72 entries per category (one per page, 2 lines per page).
"""

INSPIRATIONS = {
    "Person": [
        "Wandering old coot",
        "Tired scout",
        "Young alchemist",
        "Bread monk",
        "Adoring apprentice",
        "Lost lad",
        "Legendary sage",
        "Drunken worshipper",
        "Stocky hunter",
        "Scout sisters",
        "Lost Knight",
        "Argumentative sage",
        "Boisterous poet",
        "Elderly tanner",
        "Steady cook",
        "Cheery stablehand",
        "Oblivious cartographer",
        "Aggressive carver",
        "Cruel singer",
        "Novice shepherd",
        "Sickly ironsmith",
        "Relaxed courier",
        "Repugnant pedlar",
        "Scarred bounty hunter",
        "Intolerant herder",
        "Wise farmer",
        "Bitter archer",
        "Hot-tempered baker",
        "Pristine raider",
        "Influential collector",
        "Adored potter",
        "Sneaky cobbler",
        "Puny guard",
        "Skilled bandit",
        "Lazy weaver",
        "Clumsy messenger",
        "Legendary exile",
        "Wary crier",
        "Careless clothier",
        "Ambitious parent",
        "Furious outcast",
        "Aristocratic farrier",
        "Inquisitive lumberjack",
        "Hardened scavenger",
        "Cowardly diplomat",
        "Pathetic veteran",
        "Greedy disciple",
        "Confused fool",
        "Patronising hermit",
        "Adventurous fugitive",
        "Violent playwright",
        "Kind brewer",
        "Smug prophet",
        "Proud pilgrim",
        "Anxious bellringer",
        "Zealous student",
        "Wild thatcher",
        "Cruel charlatan",
        "Confident assassin",
        "Muddy astrologer",
        "Scabby merchant",
        "Animal worshipper",
        "Athletic warden",
        "Smart inquisitor",
        "Deceitful healer",
        "Hostile scholar",
        "Thrifty herald",
        "Friendly mercenary",
        "Armoured miner",
        "Frail herbalist",
        "Loyal sculptor",
        "Antisocial haberdasher",
    ],
    "Name": [
        "Senara",
        "Caldan",
        "Goyon",
        "Jago",
        "Medryn",
        "Harbeger",
        "Burgoyne",
        "Lumpe",
        "Knotte",
        "Ruan",
        "Demelza",
        "Chider",
        "Ludmer",
        "Prentise",
        "Valamonte",
        "Litwitte",
        "Croyle",
        "Wodwale",
        "Wattle",
        "Ragge",
        "Cradokke",
        "Sparenot",
        "Endry",
        "Arture",
        "Abbotte",
        "Crabbe",
        "Beryan",
        "Bray",
        "Ogan",
        "Tresera",
        "Dewyn",
        "Kerensa",
        "Howell",
        "Borwenna",
        "Ursell",
        "Turnbucke",
        "Myghal",
        "Plodder",
        "Tompot",
        "Reynere",
        "Gil",
        "Davith",
        "Ruskyn",
        "Ellery",
        "Gowere",
        "Roose",
        "Tyack",
        "Kernick",
        "Peryn",
        "Ezter",
        "Reyka",
        "Dorza",
        "Viralag",
        "Dorka",
        "Maldita",
        "Foxter",
        "Nieolas",
        "Brayne",
        "Kelwun",
        "Clemens",
        "Floria",
        "Hygo",
        "Andona",
        "Kirus",
        "Kapo",
        "Verner",
        "Pryer",
        "Aluna",
        "Branc",
        "Samzun",
        "Tahnet",
        "Abran",
    ],
    "Characteristic": [
        "Thunderous voice",
        "Golden hair",
        "Cold eyes",
        "Disobedient dog",
        "Formal speech",
        "House proud",
        "Battle scars",
        "Watching eyes",
        "Lice infested",
        "Shaved head",
        "Delicate clothes",
        "Mangled ear",
        "Always talking",
        "Knows everybody",
        "Sneering smile",
        "Fiery hair",
        "Pet rat",
        "Meticulously clean",
        "Fidgeting hands",
        "Haunted look",
        "Bright clothes",
        "Formal clothes",
        "No nonsense",
        "Always eating",
        "Sharp features",
        "Fine embroidery",
        "Intense speech",
        "Extremely old",
        "Smooth charmer",
        "Wild hair",
        "Few teeth",
        "Always drinking",
        "Sulky and unwashed",
        "Silver hair",
        "Extremely burly",
        "Greasy hair",
        "Wrapped up warm",
        "Wiry & lean",
        "Mud covered",
        "Overly familiar",
        "Muscular slab",
        "Amputated arm",
        "Theatrical gestures",
        "Head in the clouds",
        "Short and stocky",
        "Enthusiastic feeder",
        "Naïve questions",
        "Tall and slender",
        "Morbid embroidery",
        "Shameful eyepatch",
        "Monster tattoos",
        "Dour killjoy",
        "Flower lover",
        "Painfully slow",
        "Abrasive voice",
        "Always alert",
        "Restless limbs",
        "Always yelling",
        "Brawn over brains",
        "Red tattoos",
        "Destructive klutz",
        "Attempts mystique",
        "Huge backpack",
        "Beautifully statuesque",
        "Loves gossip",
        "Star obsessed",
        "Animal lover",
        "Piglike face",
        "Hypochondriac",
        "Fast talker",
        "Graceful hands",
        "Prosthetic legs",
    ],
    "Object": [
        "Grey lantern",
        "Moonlit honey",
        "Grief flute",
        "City coin",
        "Pain blade",
        "Weird bone",
        "Thorn spear",
        "Fang rattle",
        "Silver armour",
        "Steel rope",
        "Black cloth",
        "Limeweed",
        "Venomous rose",
        "Traveller’s hat",
        "Ghost axe",
        "Lightning wine",
        "Death woodcut",
        "Vow sunflower",
        "Cold carving",
        "Storm ring",
        "Artful cup",
        "Unbreakable compass",
        "Destiny nut",
        "Soldier’s horseshoe",
        "Bear wand",
        "Bird cauldron",
        "Rainbow beads",
        "Shadow lens",
        "Dream cup",
        "Beast idol",
        "Vanity bone",
        "Fox pipe",
        "Plague scabbard",
        "Fake tooth",
        "Nature bow",
        "Singing shell",
        "Hermit’s rope",
        "Mist club",
        "Peace stick",
        "Shame gem",
        "Mossy drum",
        "Secret key",
        "Paired chalk",
        "Creation chest",
        "Foul brooch",
        "Whistling pin",
        "River helm",
        "Silver furs",
        "Spinning goblet",
        "Vassal rod",
        "Wood mace",
        "Flesh wax",
        "War ink",
        "Tree chart",
        "Leathered bone",
        "Crystal mead",
        "Copper acorn",
        "Immovable herb",
        "Leaf sword",
        "Beggar shroud",
        "Petty candle",
        "Web net",
        "Scaled daisy",
        "City rune",
        "History pack",
        "Memory cloak",
        "Seer arrow",
        "Wolf knife",
        "Ivory mask",
        "Firebreath flask",
        "Oceanic whetstone",
        "Fear egg",
    ],
    "Beast": [
        "Smiling fox",
        "Giant magpie",
        "Grey deer",
        "Mighty newt",
        "Crowned stag",
        "Tender bloodhound",
        "Laughing shrew",
        "Redmaw wolf",
        "Draft horse",
        "Red vultures",
        "White ravens",
        "Leeches",
        "Glutton crow",
        "Moon toad",
        "Granddad louse",
        "Graveyard horse",
        "Bony zebra",
        "Tiny chameleon",
        "Ivory goat",
        "Roaring coot",
        "Longly viper",
        "Flame weasel",
        "Swiftly blackbird",
        "Leafy goose",
        "Emerald panther",
        "Oily buzzard",
        "Riding peacock",
        "Two-tailed eel",
        "Bright mole",
        "Burrowing otter",
        "Shouting pike",
        "Milk finch",
        "Clawed bees",
        "Knightly salamander",
        "Stinging crocodile",
        "Carrion stork",
        "Fanged dove",
        "Taloned heron",
        "Slow butterfly",
        "Overgrown hawk",
        "Dark swan",
        "Witchy goat",
        "Frosted hare",
        "Tiger spider",
        "Imitation sparrow",
        "Eternal scorpion",
        "Horned quail",
        "Spotted wasp",
        "Dead greyhound",
        "Sniffer bear",
        "Thorn frog",
        "Wolfy hedgehog",
        "Dust mongoose",
        "Hammer crane",
        "Fat beetle",
        "Paradise cockerel",
        "Armoured pigeon",
        "Flat owl",
        "Grim donkey",
        "Singing bull",
        "Ghost carp",
        "Listening asp",
        "Massive badger",
        "Clever tortoise",
        "Wood centipede",
        "Blind boar",
        "Watcher python",
        "Talking hyena",
        "Moss ostrich",
        "Sword rhinoceros",
        "Herbalist dog",
        "Lesser mule",
    ],
    "State": [
        "Feasting",
        "Resting",
        "Serving",
        "Drinking",
        "Stealing",
        "Sprinting",
        "Surveying",
        "Scouring",
        "Dying",
        "Repairing",
        "Nurturing",
        "Listening",
        "Sulking",
        "Confused",
        "Wandering",
        "Sick",
        "Crying",
        "Observing",
        "Intoxicated",
        "Parched",
        "Tormenting",
        "Relaxing",
        "Helping",
        "Returning",
        "Proud",
        "Starving",
        "Guarding",
        "Lost",
        "Burying",
        "Rejoicing",
        "Dutiful",
        "Empowered",
        "Awestruck",
        "Killing",
        "Competing",
        "Aiding",
        "Entangled",
        "Building",
        "Courting",
        "Tearing",
        "Arguing",
        "Envious",
        "Plotting",
        "Celebrating",
        "Washing",
        "Scared",
        "Trapped",
        "Patrolling",
        "Mourning",
        "Swimming",
        "Stalking",
        "Marching",
        "Trailing",
        "Climbing",
        "Isolating",
        "Searching",
        "Smelling",
        "Gluttonous",
        "Breaking",
        "Dashing",
        "Enfeebled",
        "Eating",
        "Thinking",
        "Travelling",
        "Bellowing",
        "Protecting",
        "Coveting",
        "Tasting",
        "Rescuing",
        "Lounging",
        "Cooking",
        "Basking",
    ],
    "Theme": [
        "Sleep",
        "Rope",
        "Names",
        "Truth",
        "Flight",
        "Healing",
        "String",
        "Cold",
        "Food",
        "Sunlight",
        "Coins",
        "Smell",
        "Questions",
        "Hearth",
        "Music",
        "Fear",
        "Dirt",
        "Anger",
        "Fire",
        "Water",
        "Shrinking",
        "Charm",
        "Blood",
        "Revenge",
        "Commands",
        "Flowers",
        "Towers",
        "Battle",
        "Sunset",
        "Memory",
        "Starlight",
        "Breaking",
        "Touch",
        "Colours",
        "Happiness",
        "Regret",
        "Moonlight",
        "Metal",
        "Location",
        "Insects",
        "Size",
        "Sharpness",
        "Numbers",
        "Fungi",
        "Sadness",
        "Weapons",
        "Vision",
        "Leaves",
        "Darkness",
        "Drink",
        "Shelter",
        "Walls",
        "Transformation",
        "Growth",
        "Dreams",
        "Ice",
        "Light",
        "Salt",
        "Warmth",
        "Frost",
        "Armour",
        "Grass",
        "Sunrise",
        "Hair",
        "Stories",
        "Repair",
        "Hearing",
        "Thirst",
        "Craft",
        "Skin",
        "Harvest",
        "Carving",
    ],
    "Dwelling": [
        "Shepherd fields",
        "Verdant treehouse",
        "Traveller’s inn",
        "Fertile farm",
        "Pigeon breeder",
        "Honey farm",
        "Cartographer hut",
        "Tea hut",
        "Hot spring",
        "Fishing pond",
        "Artisan brewery",
        "Guard’s outpost",
        "Stone quarry",
        "Lakeside lodge",
        "Toll bridge",
        "Cooling well",
        "Hidden cave",
        "Abandoned watchtower",
        "Hilltop house",
        "Salmon stream",
        "Hunting hideout",
        "Logging camp",
        "Humble fort",
        "Open market",
        "Tranquil quarry",
        "Music camp",
        "Bridge tower",
        "Jouster field",
        "Signal tower",
        "Great hall",
        "Actor encampment",
        "Trickling fountain",
        "Welcoming brewery",
        "Feasting hall",
        "Silk-farming monks",
        "Meadowside camp",
        "Patchwork tent",
        "Treetop village",
        "Walled barracks",
        "Bog village",
        "Sapling village",
        "Sage’s den",
        "Minstrel’s nook",
        "Weaver’s loft",
        "Alchemist tower",
        "Falconer’s hut",
        "Thistle gatherers",
        "Rambunctious fishery",
        "Scribe’s shelter",
        "Exile pottery",
        "Harpist gathering",
        "Stonecutting camp",
        "Citadel of pipers",
        "Silk farm",
        "Nomad camp",
        "Humble hearth",
        "Canopy outpost",
        "Knight’s rest",
        "Moonwatcher settlement",
        "Secret vineyard",
        "Reclusive perfumery",
        "Orchard village",
        "Bright windmill",
        "Shepherd tents",
        "Trapper cabin",
        "Tiny market",
        "Peaceful disciples",
        "Master hunter hut",
        "Musical hermit",
        "Guardian hearth",
        "Dreamweaver’s cocoon",
        "Philosopher tower",
    ],
    "Sanctum": [
        "Whispering brook",
        "Tranquil vista",
        "Mirrored grotto",
        "Hilltop hermitage",
        "Sun shrine",
        "Chiming bells",
        "Silent grove",
        "Blossom pond",
        "Lullaby falls",
        "Echo cave",
        "Solitude peak",
        "Stargazer hut",
        "Glittering pond",
        "Secret bay",
        "Tiny island",
        "Sparkling crags",
        "Luminous hollow",
        "Singing trees",
        "Moaning rocks",
        "Lapping waves",
        "Enchanting pool",
        "Vast plain",
        "Bracing winds",
        "Smouldering geyser",
        "Reclusive scribes",
        "Silent stairs",
        "Flickering aurora",
        "Viewing treehouse",
        "Shady grotto",
        "Flower patch",
        "Quiet path",
        "Thorn library",
        "Guiding stones",
        "Timeless pool",
        "Canyon vista",
        "Colourful flora",
        "Duck pond",
        "Serene glade",
        "Humble academy",
        "Misted grove",
        "Hallowed grove",
        "Raven roost",
        "Starfilled valley",
        "Cool meadow",
        "Whispering statuary",
        "Amber brook",
        "Vibrant glade",
        "Tranquil cove",
        "Haven of roots",
        "Timeless cavern",
        "Lullaby stream",
        "Majestic ledge",
        "Sheltered trench",
        "Salt grotto",
        "Tranquil waterfall",
        "Glittering spring",
        "Oracle font",
        "Fountain clearing",
        "Steam spring",
        "Lily field",
        "Sapphire woods",
        "Luminous pond",
        "Silent sands",
        "Fruits of clarity",
        "Aromatic pines",
        "Golden grove",
        "Lush island",
        "Youthful forest",
        "Caves of creation",
        "Ember cavern",
        "Prismatic falls",
        "Soothing thunder",
    ],
    "Monument": [
        "Royal statue",
        "Ancient obelisk",
        "Runic cairn",
        "Knight mausoleum",
        "Voyage mosaic",
        "Victory pillar",
        "Sun beacon",
        "Primal menhir",
        "Wooden arch",
        "Moon totem",
        "Sword carving",
        "Star stone",
        "Huge banner",
        "Queen’s colossus",
        "Guarded reliquary",
        "Cleaved mountain",
        "Eternal tree",
        "Titan seat",
        "Raised ship",
        "Clifftop tomb",
        "Carved names",
        "First flame",
        "Seer’s skull",
        "Buried library",
        "Heron statue",
        "Flower-adorned graves",
        "Candle-lit shrine",
        "Mossy bridge",
        "Sun brazier",
        "Spear reliquary",
        "Duelling ground",
        "Lizard statue",
        "Ancient bridge",
        "Golden yew",
        "Floral chapel",
        "Star sculpture",
        "Eternal hearth",
        "Victory arena",
        "Model city",
        "Elder tree",
        "Crystal rose",
        "Obsidian henge",
        "Story stone",
        "Looming arch",
        "Quartz pillar",
        "Sky boulder",
        "Sun garden",
        "Triple obelisk",
        "Carved monolith",
        "Lyre tree",
        "Marble mesa",
        "Kestrel statue",
        "Memory opals",
        "Seer bone reliquary",
        "Ancient throne",
        "Coin pool",
        "Golden leaf",
        "Offering plinth",
        "Silver arch",
        "Eternal beacon",
        "Pillar of ice",
        "Shell circle",
        "Crowned oak",
        "Painted cliff",
        "Worldview peak",
        "Constellation dome",
        "Roots of the world",
        "Sky spire",
        "Guardian willow",
        "Diamond aurora",
        "Echo of song",
        "Quiet flame",
    ],
    "Hazard": [
        "Choking woodland",
        "Stinging leaves",
        "Forgotten traps",
        "Razor rocks",
        "Carrion birds",
        "Salt bog",
        "Barbed gorge",
        "Sticky weeds",
        "Steam holes",
        "Raging rapids",
        "Toxic air",
        "Spiked wall",
        "Crumbling cliffs",
        "Floodplain",
        "Gulping marsh",
        "Spiked roots",
        "Slippery rocks",
        "Tight squeeze",
        "Draining climb",
        "Perilous crossing",
        "Thorn snares",
        "Fallen woods",
        "Mud slopes",
        "Spike rocks",
        "Flooded glade",
        "Bone ridges",
        "Lurking predators",
        "Slippery climb",
        "Stinging swarms",
        "Biting thorns",
        "Rat territory",
        "Sinkholes",
        "Choking dust",
        "Briar field",
        "Tangling moss",
        "Chill air",
        "Burning heat",
        "Quickmud",
        "Crumbling ground",
        "Icy rapids",
        "Fierce winds",
        "Venomous fens",
        "Razor crags",
        "Crumbling ridge",
        "Brimstone springs",
        "Vulture peaks",
        "Thorned trench",
        "Quaking ground",
        "Needle grass",
        "Numb ache on the air",
        "Draining dunes",
        "Hopeless climb",
        "Earsplitting screams",
        "Pouncing spiders",
        "Dust storm",
        "Red hail",
        "Immaterial attackers",
        "Glue bog",
        "Strangling fog",
        "Fire nettles",
        "Frostbite fog",
        "Chilling bushes",
        "Scalding heat",
        "Boulder rapids",
        "Lack of air",
        "Exhausting spores",
        "Biting muck",
        "Bloodsucking insects",
        "Parasitic worms",
        "Acidic fog",
        "Biting serpents",
        "Magma field",
    ],
    "Curse": [
        "Icy mist",
        "Shifting pit",
        "Illusory paths",
        "Heralds of doom",
        "Dark woods",
        "Ominous chimes",
        "Deafening birds",
        "Hallucinogenic spores",
        "Confounding caverns",
        "Eternal night",
        "Ghostly shadows",
        "Strange constellations",
        "Smoking stumps",
        "Taunting mirage",
        "Merciless winds",
        "Groaning earth",
        "Haunting lights",
        "Insect swarms",
        "Dead lands",
        "Rolling fog",
        "Invisible eyes",
        "Labyrinth trail",
        "Desolate moor",
        "Sulphur stink",
        "Dizzying reeds",
        "Eerie drone",
        "Dying wetland",
        "Signpost to nowhere",
        "Foul shadow",
        "Blinding spores",
        "Smoke clouds",
        "Boozy air",
        "Filth heaps",
        "Acrid swamp",
        "Taunting mirage",
        "Golden haze",
        "Yawning ravine",
        "Sudden nothingness",
        "Salt sludge",
        "Green haze",
        "Fading light",
        "Colourless woods",
        "Growing shadows",
        "Misdirecting branches",
        "Choking gorge",
        "Tainted stream",
        "Stinging shade",
        "Rippling darkness",
        "Tablet of falsehoods",
        "The Silence",
        "Gorge of sorrow",
        "Untrustworthy shadows",
        "Discordant howl",
        "Tangling shadows",
        "Pond mirage",
        "Tattered light",
        "Misleading voices",
        "Haunting reflections",
        "All light fades here",
        "Eye burning fumes",
        "Blinding blizzards",
        "Obscuring reeds",
        "Mocking clouds",
        "The haze",
        "Blinding lights",
        "Nightmare fungus",
        "Labyrinth stream",
        "Mossy air",
        "Dead-end tunnels",
        "Vortex of smoke",
        "Hopeless mirage",
        "Drizzle veil",
    ],
    "Ruin": [
        "Burned village",
        "Defiled totem",
        "Skull heap",
        "Hanging skeletons",
        "Gory painting",
        "Shattered shield",
        "Horse tomb",
        "Toppled henge",
        "Fouled garden",
        "Crumbled bridge",
        "Broken fort",
        "Impact crater",
        "Shipwreck",
        "Statuary rubble",
        "Looted shrine",
        "Ash-drowned town",
        "Smashed glade",
        "Forgotten palace",
        "Raiding debris",
        "Rotten gallows",
        "Unmarked graves",
        "Tumbled tower",
        "Bloodied altar",
        "Ash pit",
        "Smashed pottery",
        "Bloody battlefield",
        "Collapsed bridge",
        "Dead tree-shrine",
        "Dirge-horn altar",
        "Hunter remains",
        "Murder pit",
        "Collapsed wall",
        "Wicked trophies",
        "Ghosts of slaughter",
        "Vine-choked tower",
        "Flooded village",
        "Sorrowful statues",
        "Missing tower",
        "Traps and corpses",
        "Barricaded rubble",
        "Sunken abbey",
        "Haunted hamlet",
        "Lost fort",
        "Frayed bridge",
        "Scorched workshop",
        "Fallen treehouse",
        "Bloody well",
        "Broken mast",
        "Faded library",
        "Scoured trail",
        "Broken tools",
        "Crumbled mosaic",
        "Abandoned home",
        "Torn tapestry",
        "Looted caravan",
        "Screaming cave",
        "Beheaded statue",
        "Sinister altar",
        "Darkened fort",
        "Bone mausoleum",
        "Shattered stained glass",
        "Broken henge",
        "Ghostly village",
        "Scorched farm",
        "Only shadows left",
        "Smashed jail",
        "Massacre moor",
        "Desolate inn",
        "Great fallen tree",
        "Crumbled obelisk",
        "Tomb of the oathbreaker",
        "Defiled catacomb",
    ],
}
