# Generated by Django 6.0.2 on 2026-02-10 20:26

import alive.mixin
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            bases=(models.Model, alive.mixin.AliveMixin),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(models.Model, alive.mixin.AliveMixin),
        ),
        migrations.CreateModel(
            name='GameTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(models.Model, alive.mixin.AliveMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(models.Model, alive.mixin.AliveMixin),
        ),
        migrations.CreateModel(
            name='CharacterCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=4)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_cards', to='cards.card')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_cards', to='cards.character')),
            ],
            options={
                'unique_together': {('character', 'card')},
            },
            bases=(models.Model, alive.mixin.AliveMixin),
        ),
        migrations.AddField(
            model_name='card',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='cards', through='cards.CharacterCard', to='cards.character'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='cards.gametemplate')),
            ],
            bases=(models.Model, alive.mixin.AliveMixin),
        ),
        migrations.AddField(
            model_name='character',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='cards.player'),
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='cards.gametemplate')),
            ],
            bases=(models.Model, alive.mixin.AliveMixin),
        ),
        migrations.AddField(
            model_name='character',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='cards.sheet'),
        ),
    ]
