# Generated by Django 6.0.2 on 2026-02-11 17:00

import alive.mixin
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('keeper', 'Keeper'), ('player', 'Player')], default='player', max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='cards.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_memberships', to='cards.player')),
            ],
            options={
                'unique_together': {('player', 'game')},
            },
            bases=(models.Model, alive.mixin.AliveMixin),
        ),
    ]
