# Generated by Django 6.0.2 on 2026-02-12 20:46

import alive.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_gamemembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(models.Model, alive.mixin.AliveMixin),
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='tags',
        ),
        migrations.AddField(
            model_name='gametemplate',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='game_templates', to='cards.tag'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sheets', to='cards.tag'),
        ),
    ]
