# Generated by Django 6.0.2 on 2026-02-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_tag_remove_sheet_tags_gametemplate_tags_sheet_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactercard',
            name='tag',
        ),
        migrations.AddField(
            model_name='charactercard',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='character_cards', to='cards.tag'),
        ),
    ]
