# Generated by Django 6.0.2 on 2026-02-12 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_charactercard_tag_charactercard_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactercard',
            name='tags',
        ),
        migrations.AddField(
            model_name='charactercard',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_cards', to='cards.tag'),
        ),
    ]
