# Generated by Django 6.0.2 on 2026-02-14 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_remove_charactercard_tags_charactercard_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='cards.game'),
        ),
    ]
