# Generated by Django 6.0.2 on 2026-02-14 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_character_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='cards.game'),
        ),
    ]
