# Generated by Django 6.0.2 on 2026-02-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_character_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamemembership',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('keeper', 'Keeper')], default='player', max_length=20),
        ),
    ]
