# Generated by Django 6.0.2 on 2026-02-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_player_superuser_alter_gamemembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='callsign',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
