# Generated by Django 6.0.2 on 2026-02-18 18:35

import alive.mixin
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_sheet_tag_through_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cards', models.ManyToManyField(blank=True, related_name='hands', to='cards.charactercard')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hands', to='cards.character')),
            ],
            bases=(models.Model, alive.mixin.AliveMixin),
        ),
    ]
