# Generated by Django 6.0.2 on 2026-02-18 21:29

import alive.mixin
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_hand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('cards', models.ManyToManyField(blank=True, related_name='situations', to='cards.charactercard')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situations', to='cards.game')),
            ],
            bases=(models.Model, alive.mixin.AliveMixin),
        ),
    ]
