# Generated by Django 6.0.2 on 2026-02-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='assignments',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='situation',
            name='dice',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
