# Generated by Django 6.0.2 on 2026-02-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_situation_assignments_situation_dice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='charactercard',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='charactercard',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='charactercard',
            constraint=models.UniqueConstraint(condition=models.Q(('archived', False)), fields=('character', 'card'), name='unique_active_character_card'),
        ),
    ]
