# Generated by Django 6.0.2 on 2026-02-19 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_charactercard_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('level', models.PositiveSmallIntegerField(default=4)),
                ('character_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='charactercard',
            name='unique_active_character_card',
        ),
        migrations.AlterUniqueTogether(
            name='charactercard',
            unique_together={('character', 'card')},
        ),
        migrations.AddField(
            model_name='situationcard',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situation_cards', to='cards.situation'),
        ),
        migrations.RemoveField(
            model_name='charactercard',
            name='archived',
        ),
    ]
