# Generated by Django 6.0.2 on 2026-02-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_situationcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='situationcard',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
