# Generated by Django 6.0.2 on 2026-02-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0017_situation_resolved_and_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='dice_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
