# Generated by Django 6.0.2 on 2026-02-19 19:08

import alive.mixin
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0018_situation_dice_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='HexMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='cards.game')),
            ],
            bases=(models.Model, alive.mixin.AliveMixin),
        ),
    ]
