# Generated by Django 6.0.2 on 2026-02-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_hexmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='hexmap',
            name='hexes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
