# Generated by Django 6.0.2 on 2026-02-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0020_hexmap_hexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hexmap',
            name='rivers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
