# Generated by Django 6.0.2 on 2026-02-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0021_hexmap_rivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='hexmap',
            name='overlays',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
