# Generated by Django 6.0.2 on 2026-02-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0022_hexmap_overlays'),
    ]

    operations = [
        migrations.AddField(
            model_name='hexmap',
            name='barriers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
