# Generated by Django 6.0.2 on 2026-02-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0023_hexmap_barriers'),
    ]

    operations = [
        migrations.AddField(
            model_name='hexmap',
            name='notes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
