# Generated by Django 6.0.2 on 2026-02-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0024_hexmap_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='location',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='situation',
            name='situation_type',
            field=models.CharField(choices=[('situation', 'Situation'), ('event', 'Event')], default='situation', max_length=20),
        ),
    ]
