# Generated by Django 6.0.2 on 2026-02-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0025_situation_type_and_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hexmap',
            name='party_location',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='situation',
            name='situation_type',
            field=models.CharField(choices=[('situation', 'Situation'), ('note', 'Note')], default='situation', max_length=20),
        ),
    ]
