# Generated by Django 6.0.2 on 2026-02-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0026_hexmap_party_location_and_rename_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='hexmap',
            name='party_trail',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
