# Generated by Django 6.0.2 on 2026-02-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0027_hexmap_party_trail'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_time',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='situation',
            name='game_time',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
