# Generated by Django 6.0.2 on 2026-02-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0028_game_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
