# Generated by Django 6.0.2 on 2026-02-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0029_sheet_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='spare_die',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
