# Generated by Django 6.0.2 on 2026-03-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0031_sheetdefaultcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='hexmap',
            name='site_maps',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
