# Generated by Django 6.0.2 on 2026-03-04 06:09

import alive.mixin
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0032_hexmap_site_maps'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeeperNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keeper_notes', to='cards.game')),
            ],
            bases=(models.Model, alive.mixin.AliveMixin),
        ),
    ]
