# Generated by Django 6.0.2 on 2026-03-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0033_keepernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='draw_active',
            field=models.BooleanField(default=True),
        ),
    ]
