# Generated by Django 6.0.2 on 2026-03-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0034_hand_draw_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='hexmap',
            name='revealed_overlays',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
