# Generated by Django 6.0.2 on 2026-08-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0035_revealed_overlays'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercard',
            name='level_mod',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='situationcard',
            name='level_mod',
            field=models.SmallIntegerField(default=0),
        ),
    ]
