# Generated by Django 6.0.2 on 2026-08-27 09:57

import alive.mixin
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0036_card_level_mod'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_cards', to='cards.game')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cards.timelinecard')),
            ],
            options={
                'verbose_name': 'Timeline',
                'verbose_name_plural': 'Timeline',
                'ordering': ['position', 'pk'],
            },
            bases=(models.Model, alive.mixin.AliveMixin),
        ),
    ]
